// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_dkQm5fab_1AcYqWAO2of_JpfHd2phyM',
    appId: '1:310824118190:web:5d99b3a05796b9fd348a3f',
    messagingSenderId: '310824118190',
    projectId: 'codeveloper-portfolio',
    authDomain: 'codeveloper-portfolio.firebaseapp.com',
    storageBucket: 'codeveloper-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHxqUqITmmbEJYjxXKVJ0k7OH2K9bU2rE',
    appId: '1:310824118190:android:e70add75b63f0539348a3f',
    messagingSenderId: '310824118190',
    projectId: 'codeveloper-portfolio',
    storageBucket: 'codeveloper-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_EYD9w5KZF2irn22liGLLAheHVAyUyUI',
    appId: '1:310824118190:ios:eda016a2edd18752348a3f',
    messagingSenderId: '310824118190',
    projectId: 'codeveloper-portfolio',
    storageBucket: 'codeveloper-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.codeveloperPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_EYD9w5KZF2irn22liGLLAheHVAyUyUI',
    appId: '1:310824118190:ios:eda016a2edd18752348a3f',
    messagingSenderId: '310824118190',
    projectId: 'codeveloper-portfolio',
    storageBucket: 'codeveloper-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.codeveloperPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_dkQm5fab_1AcYqWAO2of_JpfHd2phyM',
    appId: '1:310824118190:web:d3be39425f63e2af348a3f',
    messagingSenderId: '310824118190',
    projectId: 'codeveloper-portfolio',
    authDomain: 'codeveloper-portfolio.firebaseapp.com',
    storageBucket: 'codeveloper-portfolio.firebasestorage.app',
  );
}
